security:
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/oauth/token
      userAuthorizationUri: http://localhost:9999/oauth/authorize
logging:
  level:
    org.springframework.web: TRACE
